version: "3"
services:
  app:
    build: .
    ports:
      - "6000:6000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
